# Form implementation generated from reading ui file 'sobre.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Uii(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 400)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(400, 0))
        self.frame.setMaximumSize(QtCore.QSize(600, 16777215))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
"background-color: qlineargradient(spread:pad, x1:0.386, y1:0.574, x2:1, y2:1, stop:0.306818 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 197));\n"
"border-radius: 3px;\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.label.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p><p align=\"center\"><span style=\" font-size:18pt;\">Participantes do Projeto</span></p><p align=\"center\"><br/></p><p align=\"center\"><span style=\" font-size:14pt;\">Dário Romão da Silva Junior</span></p><p align=\"center\"><span style=\" font-size:14pt;\">Esdras Gabriel de Alves Batista</span></p><p align=\"center\"><span style=\" font-size:14pt;\">Flávio Gabriel de Barros Torres</span></p><p align=\"center\"><span style=\" font-size:14pt;\">Renato Ferreira Barbosa</span></p><p align=\"center\"><span style=\" font-size:14pt;\">Matheus Emanuel dos Santos Aguiar Paiva</span></p><p align=\"center\"><span style=\" font-size:14pt;\">Wenderson Juvenal Lopes dos Santos</span></p><p align=\"center\"><br/></p><p align=\"center\"><span style=\" font-size:14pt; text-decoration: underline;\">3° A D.S - 2022</span></p><p align=\"center\"><br/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Uii()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
