# Form implementation generated from reading ui file 'Tela_edicao.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

#from Tela_cadastro_config import *
from PyQt6 import QtCore, QtGui, QtWidgets


class edicao(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(712, 400)
        MainWindow.setMinimumSize(QtCore.QSize(500, 400))
        MainWindow.setMaximumSize(QtCore.QSize(712, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setMinimumSize(QtCore.QSize(700, 0))
        self.frame_5.setMaximumSize(QtCore.QSize(600, 16777215))
        self.frame_5.setStyleSheet("")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_8 = QtWidgets.QFrame(self.frame_5)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 125))
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_6.setContentsMargins(65, 70, 64, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"border: 1px solid black;\n"
"border-radius:1.5px;\n"
"}")
        self.lineEdit.setFrame(False)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_6.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"border: 1px solid black;\n"
"border-radius:1.5px;\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_6.addWidget(self.lineEdit_2)
        self.verticalLayout_3.addWidget(self.frame_8)
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_7.setContentsMargins(62, 0, 61, 60)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        self.label_2.setMinimumSize(QtCore.QSize(50, 30))
        self.label_2.setMaximumSize(QtCore.QSize(50, 30))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.frame_6)
        self.comboBox.setMinimumSize(QtCore.QSize(150, 30))
        self.comboBox.setMaximumSize(QtCore.QSize(150, 30))
        self.comboBox.setStyleSheet("QComboBox{\n"
"border: 0.5px solid black;\n"
"border-radius:1.5px;\n"
"}\n"
"")
        self.comboBox.setInsertPolicy(QtWidgets.QComboBox.InsertPolicy.InsertAtBottom)
        self.comboBox.setDuplicatesEnabled(False)
        self.comboBox.setFrame(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox)
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setMinimumSize(QtCore.QSize(56, 30))
        self.label_3.setMaximumSize(QtCore.QSize(56, 30))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_6)
        self.comboBox_2.setMinimumSize(QtCore.QSize(100, 30))
        self.comboBox_2.setMaximumSize(QtCore.QSize(100, 30))
        self.comboBox_2.setStyleSheet("QComboBox{\n"
"border: 0.5px solid black;\n"
"border-radius:1.5px;\n"
"}\n"
"")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_2)
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setMinimumSize(QtCore.QSize(40, 30))
        self.label_4.setMaximumSize(QtCore.QSize(40, 30))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.spinBox = QtWidgets.QSpinBox(self.frame_6)
        self.spinBox.setMinimumSize(QtCore.QSize(45, 30))
        self.spinBox.setMaximumSize(QtCore.QSize(45, 30))
        self.spinBox.setStyleSheet("QSpinBox{\n"
"border: 1px solid black;\n"
"border-radius:1.5px;\n"
"}")
        self.spinBox.setMinimum(0)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_7.addWidget(self.spinBox)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_5.setMinimumSize(QtCore.QSize(70, 30))
        self.pushButton_5.setMaximumSize(QtCore.QSize(96, 30))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"border-radius:1.5px;\n"
"border:1px solid black;\n"
"background-color: rgb(255, 255, 255);\n"
"color: rrgb(0, 0, 0);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(250, 250, 250);\n"
"color:Black;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:black;\n"
"color:white;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_7.addWidget(self.pushButton_5)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 71))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_8.setContentsMargins(-1, -1, -1, 100)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_3.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 712, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Nome do Aluno"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Nome do Livro"))
        self.label_2.setText(_translate("MainWindow", "Gênero:"))
        self.comboBox.setCurrentText(_translate("MainWindow", "Drama"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Drama"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Ficção Científica"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Distopia"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Fantasia"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Ficção Histórica"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Romance"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Horror"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Policial"))
        self.comboBox.setItemText(8, _translate("MainWindow", "Comédia"))
        self.comboBox.setItemText(9, _translate("MainWindow", "Tecnico"))
        self.comboBox.setItemText(10, _translate("MainWindow", "Didático"))
        self.comboBox.setItemText(11, _translate("MainWindow", "Didático-Enem"))
        self.comboBox.setItemText(12, _translate("MainWindow", "Didático-Português"))
        self.comboBox.setItemText(13, _translate("MainWindow", "Didático-Sociologia"))
        self.comboBox.setItemText(14, _translate("MainWindow", "Didático-Filosofia"))
        self.comboBox.setItemText(15, _translate("MainWindow", "Didático-Química"))
        self.comboBox.setItemText(16, _translate("MainWindow", "Didático-Inglês"))
        self.comboBox.setItemText(17, _translate("MainWindow", "Didático-Biologia"))
        self.comboBox.setItemText(18, _translate("MainWindow", "Didático-Geografia"))
        self.comboBox.setItemText(19, _translate("MainWindow", "Didático-História"))
        self.comboBox.setItemText(20, _translate("MainWindow", "Didático-Física"))
        self.comboBox.setItemText(21, _translate("MainWindow", "Didático-Matemática"))
        self.label_3.setText(_translate("MainWindow", "Série/Ano:"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "1° A D.S"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "1° B D.S"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "1° A ADM"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "1° B ADM"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "2° A D.S"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "2° B D.S"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "2° A ADM"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "2° B ADM"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "3° A D.S"))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "3° B D.S"))
        self.comboBox_2.setItemText(10, _translate("MainWindow", "3° B ADM"))
        self.comboBox_2.setItemText(11, _translate("MainWindow", "3° A ADM"))
        self.label_4.setText(_translate("MainWindow", "Dias:"))
        self.pushButton_5.setText(_translate("MainWindow", "Enviar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = edicao()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
